networks:
  default:
    name: flipt
    driver: overlay
    attachable: true

services:
  flipt:
    image: docker.flipt.io/flipt/flipt:v1.43.0
    volumes:
      - ./flipt/config.yml:/etc/flipt/config/default.yml:ro
    environment:
      FLIPT_LOG_LEVEL: "DEBUG"
      FLIPT_DB_URL: ${POSTGRES_CONNECTION_STRING}
      FLIPT_CORS_ALLOWED_ORIGINS: "*"
      FLIPT_CORS_ENABLED: "true"
      FLIPT_META_CHECK_FOR_UPDATES: "true"
      FLIPT_TELEMETRY_ENABLED: "false"
      FLIPT_AUTHENTICATION_REQUIRED: "true"
      FLIPT_AUTHENTICATION_METHODS_TOKEN_ENABLED: "true"
      FLIPT_AUTHENTICATION_METHODS_BOOTSTRAP_TOKEN: ${BOOTSTRAP_TOKEN}
      FLIPT_AUTHENTICATION_SESSION_DOMAIN: ${FLIPT_AUTHENTICATION_SESSION_DOMAIN}
      FLIPT_AUTHENTICATION_SESSION_CSRF_KEY: ${FLIPT_CSRF_KEY}
      FLIPT_AUTHENTICATION_METHODS_OIDC_ENABLED: "true"
      FLIPT_AUTHENTICATION_METHODS_OIDC_EMAIL_MATCHES: ${FLIPT_ALLOWED_EMAILS_REGEX}
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_GOOGLE_ISSUER_URL: "https://accounts.google.com"
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_GOOGLE_CLIENT_ID: ${FLIPT_GOOGLE_OIDC_CLIENT_ID}
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_GOOGLE_CLIENT_SECRET: ${FLIPT_GOOGLE_OIDC_CLIENT_SECRET}
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_GOOGLE_REDIRECT_ADDRESS: ${FLIPT_GOOGLE_OIDC_REDIRECT_ADDRESS}
      FLIPT_AUTHENTICATION_METHODS_OIDC_PROVIDERS_GOOGLE_SCOPES: "email"
      FLIPT_CACHE_ENABLED: "true"
      FLIPT_METRICS_EXPORTER: "otlp"
      FLIPT_METRICS_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      FLIPT_TRACING_ENABLED: "true"
      FLIPT_TRACING_EXPORTER: "otlp"
      FLIPT_TRACING_OTLP_ENDPOINT: ${OTEL_EXPORTER_OTLP_ENDPOINT}
      OTEL_RESOURCE_ATTRIBUTES: "deployment.environment=${GO_ENV}"
    deploy:
      mode: replicated
      replicas: 3

  heartbeat:
    image: docker.elastic.co/beats/heartbeat:${ELK_VERSION}
    volumes:
      - ./heartbeat/heartbeat.yml:/usr/share/heartbeat/heartbeat.yml:ro
    user: heartbeat
    cap_add: [ "NET_RAW" ]
    command: -e --strict.perms=false
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
      FLIPT_PUBLIC_HOST: ${FLIPT_AUTHENTICATION_SESSION_DOMAIN}
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-sf",
          "-XGET",
          "localhost:5066/?pretty"
        ]

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    user: root
    command: --strict.perms=false -e
    volumes:
      - ./metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro # Only available on Linux
      - /proc:/hostfs/proc:ro # Only available on Linux
      - /:/hostfs:ro
    environment:
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: https://${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    deploy:
      mode: replicated
      replicas: 1
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-sf",
          "-XGET",
          "localhost:5066/?pretty"
        ]
