setup.kibana:
  host: '${KIBANA_HOST_PORT}'
  username: '${KIBANA_USERNAME}'
  password: '${KIBANA_PASSWORD}'

heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://flipt:8080
    - https://${FLIPT_PUBLIC_HOST}

- type: icmp
  schedule: '@every 5s'
  hosts:
    - flipt
    - ${FLIPT_PUBLIC_HOST}

processors:
- add_cloud_metadata: ~

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOST_PORT}'
  username: '${ELASTIC_USERNAME}'
  password: '${ELASTIC_PASSWORD}'

# Defines if the HTTP endpoint is enabled.
http.enabled: true
http.host: 0.0.0.0
http.port: 5066
