secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: nginx:alpine
    ports:
      - target: 443
        published: 443
      - target: 2053
        published: 2053
      - target: 2083
        published: 2083
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    networks:
      - elastic
    ulimits:
      nofile:
        soft: 15000
        hard: 15000

networks:
  elastic:
    external: true
