secrets:
  proxy.certificate:
    file: ${PROXY_CERT_PATH}
  proxy.key:
    file: ${PROXY_KEY_PATH}

services:
  proxy:
    image: nginx:alpine
    ports:
      - target: 443
        published: 443
      - target: 2053
        published: 2053
      - target: 2083
        published: 2083
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    secrets:
      - source: proxy.certificate
        target: /certs/fullchain.pem
      - source: proxy.key
        target: /certs/privkey.pem
    networks:
      - elastic
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    depends_on:
      - authnz

  authnz:
    image: skulpture/authnz-service-proxy:${TAG:-latest}
    restart: unless-stopped
    environment:
      PROXY_TARGET: https://kibana
      OIDC_PROVIDER_NAME: ${OIDC_PROVIDER_NAME}
      OIDC_ISSUER_URL: ${OIDC_ISSUER_URL}
      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}
      OIDC_REDIRECT_URL: ${OIDC_REDIRECT_URL}
      OIDC_SCOPES: email
    ulimits:
      nofile:
        soft: 200000
        hard: 200000
    deploy:
      mode: replicated
      replicas: 1

networks:
  elastic:
    external: true
