services:
  keystore:
    image: skulpture/elasticsearch:${TAG:-latest}
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-keystore.sh
    user: "0"
    volumes:
      - ${SECRETS_DIR}:/secrets
      - ./setup/:/setup/
    environment:
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}

  certs:
    image: skulpture/elasticsearch:${TAG:-latest}
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    command: bash /setup/setup-certs.sh
    user: "0"
    volumes:
      - ${SECRETS_DIR}:/secrets
      - ./setup/:/setup
