name: Build services

on:
  pull_request:
    branches: [master, staging, dev]
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.base_ref || github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: "Build Docker image: authnz"
        uses: docker/build-push-action@v5
        env:
          TAG: ${{ (env.BRANCH_NAME == 'master' && 'latest') || format('{0}-{1}', vars.KEYCLOAK_VERSION, env.BRANCH_NAME) }}
        with:
          context: "{{defaultContext}}:authnz/keycloak"
          push: false
          build-args: |
            KEYCLOAK_VERSION=${{ vars.KEYCLOAK_VERSION }}
            KEYCLOAK_CACHE=ispn
            KEYCLOAK_CACHE_STACK=kubernetes
            KEYCLOAK_DB=${{ vars.KEYCLOAK_DB }}
          tags: |
            skulpture/authnz:${{ env.TAG }}

      - name: "Build Docker image: elasticsearch"
        uses: docker/build-push-action@v5
        env:
          TAG: ${{ (env.BRANCH_NAME == 'master' && 'latest') || format('{0}-{1}', vars.ELK_VERSION, env.BRANCH_NAME) }}
        with:
          context: "{{defaultContext}}:telemetry/elasticsearch"
          push: false
          build-args: |
            ELK_VERSION=${{ vars.ELK_VERSION }}
          tags: |
            skulpture/elasticsearch:${{ env.TAG }}

      - name: "Build Docker image: kibana"
        uses: docker/build-push-action@v5
        env:
          TAG: ${{ (env.BRANCH_NAME == 'master' && 'latest') || format('{0}-{1}', vars.ELK_VERSION, env.BRANCH_NAME) }}
        with:
          context: "{{defaultContext}}:telemetry/kibana"
          push: false
          build-args: |
            ELK_VERSION=${{ vars.ELK_VERSION }}
          tags: |
            skulpture/elasticsearch:${{ env.TAG }}

      - name: "Build Docker image: apm-server"
        uses: docker/build-push-action@v5
        env:
          TAG: ${{ (env.BRANCH_NAME == 'master' && 'latest') || format('{0}-{1}', vars.ELK_VERSION, env.BRANCH_NAME) }}
        with:
          context: "{{defaultContext}}:telemetry/apm-server"
          push: false
          build-args: |
            ELK_VERSION=${{ vars.ELK_VERSION }}
          tags: |
            skulpture/apm-server:${{ env.TAG }}
