name: Preview infrastructure

on:
  pull_request:
    branches: [master, dev]
  workflow_dispatch:

jobs:
  preview:
    permissions:
      contents: read
      id-token: write

    strategy:
      matrix:
        compute: [auth, rollout, infrastructure, telemetry]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Configure GCP credentials
        id: auth
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WIF_PROVIDER }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}

      - name: "Install dependencies: ${{ matrix.compute }}"
        run: |
          ls -la
          # go mod download
        # working-directory: ${{ matrix.compute }}

      - name: "Preview stack: skulpture/shared-${{ matrix.compute }}"
        uses: pulumi/actions@v3
        with:
          command: preview
          stack-name: "skulpture/shared-${{ matrix.compute }}"
          comment-on-pr: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          work-dir: ${{ matrix.compute }}
          upsert: true
        env:
          PULUMI_ACCESS_TOKEN: ${{ vars.PULUMI_ACCESS_TOKEN }}
