name: Unit tests

on:
  pull_request:
    branches: [master, staging, dev]
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
    
      - name: Unit test (kryptos)
        run: go test ./... -cover